---
title: "p8105_hw1_xm2356"
author: "Xinyin Miao (xm2356)"
date: "2025-09-12"
output: 
  github_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(moderndive)
library(ggplot2)
```

# Problem 1

## Dataset description

The dataset has `r nrow(early_january_weather)` rows and `r ncol(early_january_weather)` columns.
The mean temperature is approximately `r round(mean(early_january_weather$temp, na.rm = TRUE), 2)`.
Variables include: `r paste(names(early_january_weather), collapse = ", ")`.

```{r}
data("early_january_weather")
```

## Scatterplot
```{r}
p_temp_time <- ggplot(early_january_weather,
                      aes(x = time_hour, y = temp, color = humid)) +
  geom_point(alpha = 0.8) +
  labs(title = "Temperature vs Time (colored by humidity)",
       x = "time_hour",
       y = "Temperature",
       color = "humid") +
  theme_minimal()

p_temp_time
```

## Export the plot
```{r}
ggsave("temp_vs_time.png", plot = p_temp_time, width = 7, height = 4)
file.exists("temp_vs_time.png")
```


# Problem 2

You can also embed plots, for example:

```{r pressure, echo=FALSE}

```


